<?
if ($index->mib!="mib") die ("Access denied");
echo "<center><font class=\"nadpis\">Muži v čiernom</font></center><br><br>";
echo "<font class=\"text\"><blockquote>&nbsp;&nbsp;&nbsp;Supertajná vladná organizácia <b>MiB</b> (teda Men in Black) je to jediné, čo stojí medzi naším pokojným životom a šmejdom tam hore. Bojujú nekončiaci boj a nik ich nepochváli. Nik totiž nevie o ich existencii. Totiž zakaždým, keď ich niekto zazrie, použijú neuralyzér (pozri nižšie).<br>&nbsp;&nbsp;&nbsp;V prvom filme na začiatku Agent K príde o Agenta D, pretože ten si chce ešte užiť trochu života na staré kolená. Agent K potrebuje nového partnera. Na konkurz dostane New Yorkského policajta Jamesa Edwardsa, ktorý ako jediný úspešne prejde testom a stane sa partnerom Agenta K. Medzitým na Zem pristane raketa s obrovským švábom, ktorý si oblečie 'šaty' z Edgara (priezvisko nebolo vo filme uvedené). Šváb terorizuje celý Manhatan, pričom hľadá princa Arquiliančanov Rosenburga, lebo ten má najväčší zdroj subatómovej energie vo vesmíre (tvaru galaxie). Rosenburga zabije, ale galaxia ostane na páse mačky Orion. Keď to šváb zistí, pôjde do márnice hľadať mačku, galaxiu zoberie a utečie. Agent K a Agent J ho však nájdu a zničia. Na koniec Agent K odíde od MiB.<br>&nbsp;&nbsp;&nbsp;V druhom filme na začiatku sa na Zem rúti malá raketa, ktorá ničí všetky planéty, ktoré jej prekážajú v ceste. Riadi ju Serleena, ktorá po pristáti na Zem vezme na seba podobu krásnej modelky. Medzitým Agent J strieda partnerov (ako blesk), až nakoniec skončí so sexichtivým psom Frankom. Keď však MiB zistia, že na Zem pristála Serleena, Agent Z pošle Agenta J po Agenta K. Keď s ním príde do MiB, aby mu vrátili pamäť, na MiB zaútočí Serleena a Agent J a Agent K utečú. Keďže však nestihli Agentovi K vrátiť pamäť, museli zájsť ku Jeepsovi. Potom si Agent K spomenul, že Serleena prišla po takzvané 'svetlo'. Vedel, že svetlo bola Laura Vasquezová, ktorá sa mimochodom páčila Agentovi J, a preto jej naposledy nevymazal pamäť. Nakoniec agenti doviedli Lauru na istú budovu, odkiaľ ju mala odviezť raketa. Medzitým sa Serleena pokúsila ešte raz zaútčiť, ale nepodarilo sa to. Keďže výbuch, ktorý nastal potom, keď agenti zabili Serleenu, neunikol ani jednému obyvataľovi mesta, Agent J si nevedel dať rady, ako im vymazať pamäť. Agent K však vedel stále viac, ako Agent J: Socha Slobody je totiž ďalší neuraluzér.</blockquote></font>";
echo "<center><font class=\"nadpis\">Neuralyzér</font></center><br><br>";
echo "<font class=\"text\"><blockquote>&nbsp;&nbsp;&nbsp;Neuralyzér Muži v čiernom používajú, keď ich nejaký náhodný svedkovia uvidia pri ich práci. Stačí len nastaviť čas, nasadiť okuliare a stlačiť.</blockquote></font>";
echo "<center><table border=\"0\"><tr><td><a href=\"images/neuralyzer1.jpg\" target=\"_new\"><img src=\"images/neuralyzer1_s.jpg\" border=\"0\"></a></td><td>";
echo "<a href=\"images/neuralyzer2.jpg\" target=\"_new\"><img src=\"images/neuralyzer2_s.jpg\" border=\"0\"></a></td><td>";
echo "<a href=\"images/neuralyzer3.jpg\" target=\"_new\"><img src=\"images/neuralyzer3_s.jpg\" border=\"0\"></a></td><td>";
echo "<a href=\"images/neuralyzer4.jpg\" target=\"_new\"><img src=\"images/neuralyzer4_s.jpg\" border=\"0\"></a></td></tr></table></center>";
?>